### PR TITLE
(IGNORE) Dummy change

### PR DESCRIPTION
**Pull request by totten**
Dummy change to check current disposition of PR test runs.

### CODE REVIEW

**Comment by totten** [comment]
@seamuslee Two observations on this:

1. It seems that [CiviWP\HookTest](https://github.com/civicrm/civicrm-wordpress/blob/master/tests/phpunit/CiviWP/HookTest.php#L22) is failing in CI. Locally, it passes in `bknix-min`/`php72` but fails in `bknix-dfl`/`php80` (showing the same error as CI).
2. When you drill down on the results (Github => "Details" => Jenkins), it doesn't show the `HookTest` failure. However, if I poke on the test node, I can see that the JUnit XML file is created at `~/workspace/CiviCRM-WordPress-PR/junit/phpunit_wordpress.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CiviCRM-WordPress Test Suite" tests="2" assertions="3" errors="1" failures="0" skipped="0" time="0.000949">
    <testsuite name="CiviWP\HookTest" file="/home/jenkins/bknix-dfl/build/wp-264-42efj/web/wp-content/plugins/civicrm/tests/phpunit/CiviWP/HookTest.php" tests="1" assertions="1" errors="1" failures="0" skipped="0" time="0.000531">
      <testcase name="testFoo" class="CiviWP\HookTest" classname="CiviWP.HookTest" file="/home/jenkins/bknix-dfl/build/wp-264-42efj/web/wp-content/plugins/civicrm/tests/phpunit/CiviWP/HookTest.php" line="14" assertions="1" time="0.000531">
        <error type="PHPUnit\Framework\Error\Warning">CiviWP\HookTest::testFoo
Undefined array key "hook_was_called"

/home/jenkins/bknix-dfl/build/wp-264-42efj/web/wp-content/plugins/civicrm/tests/phpunit/CiviWP/HookTest.php:22
/home/jenkins/bknix-dfl/extern/phpunit8/phpunit8.phar:671
</error>
      </testcase>
    </testsuite>
    <testsuite name="CiviWP\PhpVersionTest" file="/home/jenkins/bknix-dfl/build/wp-264-42efj/web/wp-content/plugins/civicrm/tests/phpunit/CiviWP/PhpVersionTest.php" tests="1" assertions="2" errors="0" failures="0" skipped="0" time="0.000418">
      <testcase name="testConstantMatch" class="CiviWP\PhpVersionTest" classname="CiviWP.PhpVersionTest" file="/home/jenkins/bknix-dfl/build/wp-264-42efj/web/wp-content/plugins/civicrm/tests/phpunit/CiviWP/PhpVersionTest.php" line="15" assertions="2" time="0.000418"/>
    </testsuite>
  </testsuite>
</testsuites>
```

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@totten ok I got it to show the hook test failure properly now, But still a little miffed about the test failure in of its self

**Comment by totten** [comment]
Yeah, I think an issue may be that we don't run `CiviWP` suite in any of the regular matrices? 

We probably should have signal for this in the regular matrices - eg updating https://test.civicrm.org/job/CiviCRM-E2E-Matrix/ with:

```bash
case "$BLDTYPE" in 
  "wp-demo") SUITES="$SUITES phpunit-wordpress" ; ;;
  "drupal-clean") SUITES="$SUITES phpunit-drupal" ; ;;
  "backdrop-clean") SUITES="$SUITES phpunit-backdrop" ; ;;
esac
```

I've requested a [small run](https://test.civicrm.org/job/CiviCRM-E2E-Matrix/4112/) for `(master)x(d7,wp,bd)x(min,max)`, but there's a bit of queue, so it may take time to get to it..

**Pull request closed without merging**
