### PR TITLE
Test moving wpload -- DO NOT MERGE 

### PR DESCRIPTION
**Pull request by kcristiano**
Force test run

### CODE REVIEW

**Comment by kcristiano** [comment]
jenkins test this please

**Comment by kcristiano** [comment]
@seamuslee001 @totten I created this to test the build and test of one area of #260 and this says it failed but I see no errors in jenkins.   Can you help me out on what is going on?

**Comment by kcristiano** [comment]
related https://github.com/civicrm/civicrm-buildkit/pull/664

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
@kcristiano this is the error to resolve it I think you need to bring across this as well https://github.com/civicrm/civicrm-wordpress/pull/260/files#diff-4d9ca14692330af02dcd128346ed1a2150b8543c7acbc103d140af0abddb96f5R454

```
+++ wp plugin activate civicrm
Plugin 'civicrm' activated.
Success: Activated 1 of 1 plugins.
+++ wp eval '$c=[civi_wp()->admin, "add_wpload_setting"]; if (is_callable($c)) $c();'
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```

**Comment by kcristiano** [comment]
Thanks @seamuslee001 I missed that in the logs.  

Looks like the setting we added for E2E test works in current versions, but if we move the action to fire early (as it should) we then get a fatal when building.  Oddly I do not get this locally when building.

Let me add a version check and wrap it around the `wp eval '$c=[civi_wp()->admin, "add_wpload_setting"]; if (is_callable($c)) $c();` statement and only run if civiver is < 5.46

**Pull request closed without merging**
