### PR TITLE
[WIP][DO NOT MERGE] Allowed user defined shortcodes to be rendered

### PR DESCRIPTION
**Pull request by Edzelopez**
Overview
----------------------------------------
This PR will add support to render user defined shortcodes in WordPress when specified through extensions.

Before
----------------------------------------
Code returns abruptly with an error saying "Do not know how to handle this shortcode"

After
----------------------------------------
Code renders the shortcode based on filters specified in the extension.

Technical Details
----------------------------------------
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

Comments
----------------------------------------
_Anything else you would like the reviewer to note_

### CODE REVIEW

**Comment by kcristiano** [comment]
@christianwach Can you take a look at this?

**Comment by JoeMurray** [comment]
@Edzelopez please update the overview. Also could you or @monish respond to @christianwach promptly?

**Comment by Edzelopez** [comment]
Thanks for looking at this @christianwach and apologies for the delay. You are right, I intend to allow the use of user defined shortcodes before the control is broken by the switch case. I will modify the code to allow logic to flow to the filter rather than declaring it a second time above.

**Comment by christianwach** [comment]
@Edzelopez That would be great :)

**Comment by christianwach** [comment]
This can be closed in favour of #134 which implements code based on the advice that I gave in [my comment on this PR](https://github.com/civicrm/civicrm-wordpress/pull/131#issuecomment-404189434).

**Comment by kcristiano** [comment]
closing, #134 completes the work suggested

**Pull request closed without merging**
