### PR TITLE
Change PHP keywords to comply with PSR2

### PR DESCRIPTION
**Pull request by mullikine**
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

### CODE REVIEW

**Comment by kcristiano** [comment]
also see  https://github.com/civicrm/civicrm-drupal/pull/570

**Comment by mullikine** [comment]
> also see [civicrm/civicrm-drupal#570](https://github.com/civicrm/civicrm-drupal/pull/570)

I've found 61 instances of lowercase constants in this repository. If you wish I can remake this PR to adhere to the Drupal standard rather than PSR-2.

**Comment by kcristiano** [comment]
@mullikine Thanks for the PR I added the note so I wouldn't hunt for it later.   We are trying to standardize the code standards on this repo.  

@christianwach what do you think?   Seems like WP convention is contrary to Drupal:
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', false );
define( 'WP_DEBUG_DISPLAY', true );
```

**Comment by christianwach** [comment]
@kcristiano Code style is largely a matter of taste. I'd have preferred the whole CiviCRM-WordPress repo to conform to [WordPress standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/), but the code often gets "corrected" to conform to CiviCRM standards. In the end, I'm agnostic about conventions -- the `.editorconfig` file allows IDEs to adapt.

**Comment by kcristiano** [comment]
Closing until a decision is made to standardize for all repos

**Pull request closed without merging**
