### PR TITLE
dev/wordpress#49 Prevent 301 redirects if 'page=CiviCRM'

### PR DESCRIPTION
**Pull request by mecachisenros**
Overview
----------------------------------------
Prevents old URLs like `example.org/civicrm/?page=CiviCRM&q=what/ever/path&reset=1`
being redirected to `example.org/civicrm/?civiwp=CiviCRM&q=what/ever/path&reset=1`.

Before
----------------------------------------
Old URLs like `example.org/civicrm/?page=CiviCRM&q=what/ever/path&reset=1` would be 301 redirected.

After
----------------------------------------
No redirects.

Technical Details
----------------------------------------
Filters the request right after WP's parsed it and replaces the 'page' query variable with 'civiwp' if applicable.

Comments
----------------------------------------
I think this should be an addition to @christianwach work on #194 because one could prevent WP from parsing the request (via hooks) which will not trigger this.

### CODE REVIEW

**Comment by christianwach** [comment]
@mecachisenros Thanks for starting on this 👍 I think you can remove [this code](https://github.com/civicrm/civicrm-wordpress/blob/396d83623b17751027a5b9d76c60d097fb472943/civicrm.php#L619-L625) which should be unnecessary with you additions.

**Comment by mecachisenros** [comment]
@christianwach I think that code should remain as a fallback, the reason being one could [bypass](https://developer.wordpress.org/reference/hooks/do_parse_request/) WP from parsing the query which would prevent my code from running, and that would _break_ the page.

**Comment by christianwach** [comment]
@mecachisenros Gotcha - fair point.

**Comment by kcristiano** [comment]
Did `r-run` on 5.26 site and all worked as expected.

I also did an `r-run` with a site upgraded from 5.25 to 5.26 and I could not 'break it.

I have created recurring payments to track if this will allow existing URLs in the old page format to redirect with payload.

Either way, this is far better merged.

**Pull request merged**
