### PR TITLE
NFC For testing the tests

### PR DESCRIPTION
**Pull request by kcristiano**
Testing the tests

### CODE REVIEW

**Comment by kcristiano** [comment]
test this please

**Comment by kcristiano** [comment]
test this please

**Comment by totten** [comment]
Oh, interesting. So we're getting this test failure on 5.47+ but not on 5.46? https://test.civicrm.org/job/CiviCRM-E2E-Matrix/

**Comment by kcristiano** [comment]
@totten I missed that piece of info.   I want to merge the other PR, but have delayed due to failing tests.  I do need some help figuring this out.

**Comment by totten** [comment]
OK, I'll see if I can dig up some more on the cause/origin.

**Comment by totten** [comment]
@kcristiano I believe failure in `E2E_Extern_AuthxRestTest.testNotCMSUser_q` does not indicate an actual regression. More discussion and proposed resolution in https://github.com/civicrm/civicrm-core/pull/22817

**Pull request closed without merging**
