### PR TITLE
Fix wp-cli upgrade command failing without legacy settings file

### PR DESCRIPTION
**Pull request by gpoole**
Overview
----------------------------------------
Fixes the wp-cli `wp civicrm upgrade` command failing with the error `Unable to locate settings file at wp-content/plugins/civicrm/civicrm.settings.phpor at wp-content/uploads/civicrm/civicrm.settings.php` if only one of those two files exists.

Before
----------------------------------------

The upgrade command currently fails on my install with a `Unable to locate settings file at` error about not being able to find `civicrm.settings.php` file in one of two locations:
- `$wp_root/wp-content/plugins/civicrm/civicrm.settings.php`
- `$wp_root/wp-content/uploads/civicrm/civicrm.settings.php`

The check assume that _both_ files exist, which wasn't true for my install (I only have it in the non-legacy location).

After
----------------------------------------

The legacy settings are loaded only if the new settings file doesn't exist. If both exist, only the new settings file is used. If the legacy settings file doesn't exist, there is no error.

### CODE REVIEW

**Comment by christianwach** [comment]
@gpoole Thanks! Changes look good to me.

**Comment by seamuslee001** [comment]
Jenkins add to whitelist

**Comment by kcristiano** [comment]
@gpoole Thanks for the PR.

I did an `r-run`

- Created a clean WP CiviCRM Site
  - WP 5.5.1 CiviCRM 5.29.0
- created new tarball for CiviCRM 5.31.alpha using distmaker
- tested in webroot `wp cv upgrade --zipfile='~/projects/buildkit/build/dist/out/tar/civicrm-5.31.alpha1-wordpress.zip'`
  - failed as expected with error that  settings file could not be found
- Added PR to `wp-cli/civicrm.php`
- attempted upgrade from webroot `wp cv upgrade --zipfile='~/projects/buildkit/build/dist/out/tar/civicrm-5.31.alpha1-wordpress.zip'`
 
```
The upgrade process involves - 
1. Backing up current CiviCRM code as => /srv/www/buildkit/wpclean/web/../backup/plugins/20200905143345/civicrm
2. Backing up database as => /srv/www/buildkit/wpclean/web/../backup/plugins/20200905143345/civicrm.sql
3. Unpacking tarfile to => /srv/www/buildkit/wpclean/web/wp-content/plugins/
4. Executing civicrm/upgrade?reset=1 just as a browser would.

Do you really want to continue? [y/n] y

Success: 1. Code backed up.
Success: Exported to /srv/www/buildkit/wpclean/web/../backup/plugins/20200905143345/civicrm.sql
Success: 2. Database backed up.
Extracting zip archive ...
```

However, on returning to site, No CiviCRM.   Go to the plugins page:

`The plugin civicrm/civicrm.php has been deactivated due to an error: Plugin file does not exist.`

I then restored to 5.29 and started again.  After applying patch: ran `wp cv upgrade --zipfile='/home/kcristiano/projects/buildkit/build/dist/out/tar/civicrm-5.31.alpha1-wordpress.zip'
`
Output:

```
The upgrade process involves - 
1. Backing up current CiviCRM code as => /srv/www/buildkit/wpclean/web/../backup/plugins/20200905144443/civicrm
2. Backing up database as => /srv/www/buildkit/wpclean/web/../backup/plugins/20200905144443/civicrm.sql
3. Unpacking tarfile to => /srv/www/buildkit/wpclean/web/wp-content/plugins/
4. Executing civicrm/upgrade?reset=1 just as a browser would.

Do you really want to continue? [y/n] y

Success: 1. Code backed up.
Success: Exported to /srv/www/buildkit/wpclean/web/../backup/plugins/20200905144443/civicrm.sql
Success: 2. Database backed up.
Extracting zip archive ...
Success: 3. Archive unpacked.
Copying civicrm.settings.php to /srv/www/buildkit/wpclean/web/wp-content/plugins/civicrm/..
Error: Failed to copy file
```

On Loading CiviCRM I can see the upgrade did not occur:

image

The error looks related to https://github.com/gpoole/civicrm-wordpress/blob/patch-1/wp-cli/civicrm.php#L1030

```php
WP_CLI::success( '3. Archive unpacked.' );

      WP_CLI::line( 'Copying civicrm.settings.php to ' . $project_path . '..' );
      define( 'CIVICRM_SETTINGS_PATH', $project_path . 'civicrm.settings.php' );

      if ( ! copy( $backup_dir . '/civicrm/civicrm.settings.php', CIVICRM_SETTINGS_PATH ) ) {
        return WP_CLI::error( 'Failed to copy file' );
      }
```

Can you take a look at this?  I suspect the copying back of the settings file is to ensure that if it is still in the code directory, we can proceed.   It may be time to move the settings file on upgrade - the settings file really should not be in the code directory any longer, I think we moved that in V 4.6

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by kcristiano** [comment]
This needs a rebase.   I am closig.  Once you  fix the error and rebase please resubmit

**Pull request closed without merging**
