### PR TITLE
Bump minimum install version to be 7.1 (Do not merge until 5.24 RC is cut)

### PR DESCRIPTION
**Pull request by seamuslee001**
Overview
----------------------------------------
Bumps the minimum PHP version needed to be 7.1 

ping @totten @eileenmcnaughton

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by agh1** [comment]
For cross-referencing, see [dev/core#1528](https://lab.civicrm.org/dev/core/issues/1528)

**Comment by seamuslee001** [comment]
ping @kcristiano

**Comment by seamuslee001** [comment]
Merging this to match Core

**Pull request merged**
