### PR TITLE
Fix UTC offsets when retrieving timezone string in WordPress

### PR DESCRIPTION
**Pull request by christianwach**
Overview
----------------------------------------
Fixes [this issue on Lab](https://lab.civicrm.org/dev/wordpress/-/issues/121).

Before
----------------------------------------
In WordPress, one can choose e.g. `UTC+4` as the site's timezone. This results in no value being returned by `get_option('timezone_string')` which may lead to unexpected results in CiviCRM.

After
----------------------------------------
When choosing e.g. `UTC+4` in WordPress, a deprecated (but still currently valid) `Etc/UTC-4` timezone string is used.

Comments
----------------------------------------
There is a companion PR in [the CiviCRM-Core repo](https://github.com/civicrm/civicrm-core/pull/26604).

### CODE REVIEW

**Comment by christianwach** [comment]
Gah, the old `Undefined array key "page"` test failure 🤷

**Comment by demeritcowboy** [comment]
I did a quick little run. For example creating an activity in the UI defaults the activity date to the wrong time currently, and with the PR sets it according to the configured offset.

**Comment by demeritcowboy** [comment]
jenkins retest this please

**Comment by kcristiano** [comment]
Failing Check is unrelated.

Have done multiple `r-run` via API and different forms we use on client sites.  All looks good.

Will merge once https://github.com/civicrm/civicrm-core/pull/26604   is merged.

**Pull request merged**
