### PR TITLE
dev/core#1681 Block sites from being able to upgrade CiviCRM if runni…

### PR DESCRIPTION
**Pull request by seamuslee001**
…ng MySQL versions below 5.6.5

ping @totten @kcristiano

### CODE REVIEW

**Comment by seamuslee001** [comment]
Jenkins re test this please

**Comment by kcristiano** [comment]
I've done an `r-run` and this PR does work as intended.   I am unclear if this will prevent MariaDB 10.0 (which IIRC is mysql 5.5 compatible) from loading properly.  I think any maria versions above 10.1 will be fine, but I am unclear about 10.0.  

Also see - https://chat.civicrm.org/civicrm/pl/idcorgxngiygmqbzqmk7pc8e1r  for a discussion on whether we want the check on all page loads.  My inclination is we are better off testing on install upgrade.  The only riskj I see is if a site is moved from a later version of MySQL to an earlier one - but that should cuase pain unrelated to CiviCRM.

**Comment by seamuslee001** [comment]
@totten ^

**Comment by seamuslee001** [comment]
Closing this as per comment https://github.com/civicrm/civicrm-core/pull/17558#issuecomment-646932490

**Pull request closed without merging**
