### PR TITLE
Allow render shortcodes outside of the post_content

### PR DESCRIPTION
**Pull request by marcelo2605**
A practical situation: I had some shortcodes stored in the postmeta table and I need to render them in specific places on a page. Using the `civicrm_has_shortcode` filter, I can check if the post has any other shortcode. And with the `civicrm_content_shortcode` filter I can include these shortcodes in the list of shortcodes to be rendered.

It works better using `Remain in Shortcode Mode`.

### CODE REVIEW

**Comment by marcelo2605** [comment]
Sure @christianwach! The profile IDs are stored in a custom field created by ACF. This is how I am using these filters:

``` php
add_filter('civicrm_has_shortcode', function ($has_shortcode) {
    if (!is_page()) {
        return $has_shortcode;
    }

    $sections = get_field('page_sections');
    $has_shortcode = array_filter(Arr::pluck($sections, 'forms'));

    return $has_shortcode;
});

add_filter('civicrm_content_shortcode', function ($content) {
    if (!is_page()) {
        return $content;
    }

    $sections = get_field('page_sections');
    $formIDs = array_filter(Arr::pluck($sections, 'forms'));
    if (!$formIDs) {
        return $content;
    }

    foreach ($formIDs as $formID) {
        $shortcode = generateCiviShortcode(absint($formID)); // e.g. [civicrm component="profile" gid="1" mode="create" hijack="1"]
        $content .= $shortcode;
    }

    return $content;
});
```
Then, inside my view, I can render the shortcodes using `do_shortcode()`.

**Comment by marcelo2605** [comment]
@christianwach `add_action( 'wp_enqueue_scripts', array( civi_wp(), 'front_end_page_load' ), 100 );` load all the CSS and JS dependencies, but does not allow shortcodes saved outside main content to be rendered. 

This happens because of [this conditional](https://github.com/civicrm/civicrm-wordpress/blob/000ee07e95acff6bcb2a0f477683489a53335a0d/includes/civicrm.shortcodes.php#L151). It only consider shortcodes inside `$post->post_content`.

**Comment by christianwach** [comment]
@marcelo2605 Sorry for the delay in looping back to this. Here's what I did to satisfy myself that [the technique I linked you to](https://civicrm.stackexchange.com/questions/16718/enable-use-of-do-shortcode-when-using-civicrm-and-wordpress-templates) works as expected without additional code:

* I added an ACF field to the Page post type which defines a CiviCRM Profile ID. 
* I created a test Page and a template for the Page
* For simplicity, I put `1` as the custom field value stored for my test Page.

The top of my template file looks like this:

```php
<?php
/**
 * Template Name: Page for testing
 */

add_action( 'get_header', 'force_civi_scripts_to_load' );
function force_civi_scripts_to_load() {
  add_action( 'wp_enqueue_scripts', [ civi_wp(), 'front_end_page_load' ], 100 );
}

get_header(); ?>
```

And my code in The Loop:

```php
$gid = get_field( 'profile_id' );
if ( ! empty( $gid ) ) {
  echo do_shortcode( '[civicrm component="profile" gid="' . $gid . '" mode="create" hijack="0"]' );
}
```

I view my page and see:

Screenshot 2023-09-15 at 12 11 52

The CiviCRM Profile is fully functional without the need for this PR.

**Comment by marcelo2605** [comment]
Hey @christianwach, sorry for the delay and thanks for your feedback. I haven't had time to review the PR yet, but I'm testing your first suggestion. It's working except for a single point: when the Shortcode Display Mode is set to "Remain in Shortcode Mode" and I'm using the shortcode to render a contribution page, the WordPress Base Page (`/civicrm`) is loaded after click on "Review your Contribution". Could you test this scenario? Let me know if you need more details.

**Comment by shaneonabike** [comment]
@kcristiano was it an accident you closed this one? I see that @christianwach asked @marcelo2605 to do a merge accept on his changes and then @christianwach would merge it?

I think it could be a good addition, but I don't want to trump your guys work here...

**Comment by christianwach** [comment]
@shaneonabike The PR was closed due to a lack of activity for 8 months. The suggestions weren't implemented and it could not be merged as it stands. FWIW, I agree that the idea is good in principle.

**Comment by kcristiano** [comment]
@shaneonabike I agree with the above, in addition we will need extensive testing do to issues we have had with civicrm content outside of post_content in the past.  If you want to take a look  at this again and update the PR, we will review.

**Comment by christianwach** [comment]
@kcristiano I'm on it. I think the title and description of the PR don't really describe the use case.

**Pull request closed without merging**
